server:
  port: 8000
spring:
  application:
    name: ag-login
  datasource:
    url: jdbc:mysql://localhost:3306/hello?useUnicode=true&characterEncoding=UTF8&serverTimezone=CTT
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initial-size: 1
      max-wait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreParedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: localhost
    password: 123456
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mapper

