spring:
  profiles:
    active: dev
    include: mybatis
---
server:
  port: 8080
spring:
  profiles: bate

---
server:
  port: 8888
  jetty:
    acceptors: 2
    selectors: 4
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 3
      max-active: 20
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true:druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
    driver-class-name: com.mysql.cj.jdbc.Driver

---
server:
  port: 80
  jetty:
    acceptors: 2
    selectors: 4
spring:
  profiles: product
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 3
      max-active: 20
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true:druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
    driver-class-name: com.mysql.cj.jdbc.Driver